CREATE database mydatabase;
USE mydatabase;

SHOW TABLES;

SELECT * 
FROM mytable 
LIMIT 20;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,
       SUM(purchase_amount) AS revenue
FROM mytable
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, 
       purchase_amount
FROM mytable
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM mytable
  );


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS average_product_rating
FROM mytable
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.

SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM mytable
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more?

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(
           100.0 * SUM(
               CASE 
                   WHEN discount_applied = 'Yes' THEN 1 
                   ELSE 0 
               END
           ) / COUNT(*),
           2
       ) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal.

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases <= 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM mytable
)

SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. Are repeat buyers also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;